/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 53
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__blank_line = 1,
  sym_pod_command = 2,
  aux_sym_begin_paragraph_token1 = 3,
  sym_begin_command = 4,
  sym_end_command = 5,
  sym_for_command = 6,
  sym_format_name = 7,
  aux_sym_command_paragraph_token1 = 8,
  sym_command = 9,
  sym_cut_command = 10,
  sym__eol = 11,
  sym__start_command = 12,
  sym__start_plain = 13,
  sym__start_verbatim = 14,
  sym__content_plain = 15,
  sym__intseq_letter = 16,
  sym__intseq_start = 17,
  sym__intseq_end = 18,
  sym__data_section = 19,
  sym_pod = 20,
  sym_pod_paragraph = 21,
  sym_begin_paragraph = 22,
  sym_for_paragraph = 23,
  sym_command_paragraph = 24,
  sym_plain_paragraph = 25,
  sym_verbatim_paragraph = 26,
  sym_cut_paragraph = 27,
  sym_content = 28,
  aux_sym__content = 29,
  sym_interior_sequence = 30,
  sym_sequence_letter = 31,
  aux_sym_pod_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__blank_line] = "_blank_line",
  [sym_pod_command] = "pod_command",
  [aux_sym_begin_paragraph_token1] = "begin_paragraph_token1",
  [sym_begin_command] = "begin_command",
  [sym_end_command] = "end_command",
  [sym_for_command] = "for_command",
  [sym_format_name] = "format_name",
  [aux_sym_command_paragraph_token1] = "command_paragraph_token1",
  [sym_command] = "command",
  [sym_cut_command] = "cut_command",
  [sym__eol] = "_eol",
  [sym__start_command] = "_start_command",
  [sym__start_plain] = "_start_plain",
  [sym__start_verbatim] = "_start_verbatim",
  [sym__content_plain] = "_content_plain",
  [sym__intseq_letter] = "_intseq_letter",
  [sym__intseq_start] = "<",
  [sym__intseq_end] = ">",
  [sym__data_section] = "data",
  [sym_pod] = "pod",
  [sym_pod_paragraph] = "pod_paragraph",
  [sym_begin_paragraph] = "begin_paragraph",
  [sym_for_paragraph] = "for_paragraph",
  [sym_command_paragraph] = "command_paragraph",
  [sym_plain_paragraph] = "plain_paragraph",
  [sym_verbatim_paragraph] = "verbatim_paragraph",
  [sym_cut_paragraph] = "cut_paragraph",
  [sym_content] = "content",
  [aux_sym__content] = "_content",
  [sym_interior_sequence] = "interior_sequence",
  [sym_sequence_letter] = "sequence_letter",
  [aux_sym_pod_repeat1] = "pod_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__blank_line] = sym__blank_line,
  [sym_pod_command] = sym_pod_command,
  [aux_sym_begin_paragraph_token1] = aux_sym_begin_paragraph_token1,
  [sym_begin_command] = sym_begin_command,
  [sym_end_command] = sym_end_command,
  [sym_for_command] = sym_for_command,
  [sym_format_name] = sym_format_name,
  [aux_sym_command_paragraph_token1] = aux_sym_command_paragraph_token1,
  [sym_command] = sym_command,
  [sym_cut_command] = sym_cut_command,
  [sym__eol] = sym__eol,
  [sym__start_command] = sym__start_command,
  [sym__start_plain] = sym__start_plain,
  [sym__start_verbatim] = sym__start_verbatim,
  [sym__content_plain] = sym__content_plain,
  [sym__intseq_letter] = sym__intseq_letter,
  [sym__intseq_start] = sym__intseq_start,
  [sym__intseq_end] = sym__intseq_end,
  [sym__data_section] = sym__data_section,
  [sym_pod] = sym_pod,
  [sym_pod_paragraph] = sym_pod_paragraph,
  [sym_begin_paragraph] = sym_begin_paragraph,
  [sym_for_paragraph] = sym_for_paragraph,
  [sym_command_paragraph] = sym_command_paragraph,
  [sym_plain_paragraph] = sym_plain_paragraph,
  [sym_verbatim_paragraph] = sym_verbatim_paragraph,
  [sym_cut_paragraph] = sym_cut_paragraph,
  [sym_content] = sym_content,
  [aux_sym__content] = aux_sym__content,
  [sym_interior_sequence] = sym_interior_sequence,
  [sym_sequence_letter] = sym_sequence_letter,
  [aux_sym_pod_repeat1] = aux_sym_pod_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym_pod_command] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_begin_paragraph_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_begin_command] = {
    .visible = true,
    .named = true,
  },
  [sym_end_command] = {
    .visible = true,
    .named = true,
  },
  [sym_for_command] = {
    .visible = true,
    .named = true,
  },
  [sym_format_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_command_paragraph_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_cut_command] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym__start_command] = {
    .visible = false,
    .named = true,
  },
  [sym__start_plain] = {
    .visible = false,
    .named = true,
  },
  [sym__start_verbatim] = {
    .visible = false,
    .named = true,
  },
  [sym__content_plain] = {
    .visible = false,
    .named = true,
  },
  [sym__intseq_letter] = {
    .visible = false,
    .named = true,
  },
  [sym__intseq_start] = {
    .visible = true,
    .named = false,
  },
  [sym__intseq_end] = {
    .visible = true,
    .named = false,
  },
  [sym__data_section] = {
    .visible = true,
    .named = true,
  },
  [sym_pod] = {
    .visible = true,
    .named = true,
  },
  [sym_pod_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_begin_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_for_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_command_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_cut_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__content] = {
    .visible = false,
    .named = false,
  },
  [sym_interior_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence_letter] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_pod_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_command = 1,
  field_format = 2,
  field_letter = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_command] = "command",
  [field_format] = "format",
  [field_letter] = "letter",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 1},
  [5] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_command, 1},
  [1] =
    {field_letter, 0},
  [2] =
    {field_format, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = sym_content,
  },
  [5] = {
    [5] = sym_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 7,
  [11] = 9,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 22,
  [25] = 23,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 32,
  [52] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '=') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == ':' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == 'b') ADVANCE(23);
      if (lookahead == 'c') ADVANCE(32);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == 'p') ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == 'b') ADVANCE(23);
      if (lookahead == 'c') ADVANCE(32);
      if (lookahead == 'f') ADVANCE(28);
      if (lookahead == 'p') ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(9);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__blank_line);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_pod_command);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_begin_paragraph_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_begin_command);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_end_command);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_end_command);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_for_command);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_format_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_command_paragraph_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'd') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'd') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'g') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'i') ADVANCE(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'n') ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'o') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'o') ADVANCE(22);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'r') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 't') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'u') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_command);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_cut_command);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 10, .external_lex_state = 2},
  [2] = {.lex_state = 10, .external_lex_state = 2},
  [3] = {.lex_state = 10, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 4},
  [6] = {.lex_state = 0, .external_lex_state = 4},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 5},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 10, .external_lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 10, .external_lex_state = 2},
  [15] = {.lex_state = 10, .external_lex_state = 2},
  [16] = {.lex_state = 10, .external_lex_state = 2},
  [17] = {.lex_state = 10, .external_lex_state = 2},
  [18] = {.lex_state = 10, .external_lex_state = 2},
  [19] = {.lex_state = 10, .external_lex_state = 2},
  [20] = {.lex_state = 10, .external_lex_state = 2},
  [21] = {.lex_state = 10, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 4},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 4},
  [26] = {.lex_state = 9, .external_lex_state = 6},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 0, .external_lex_state = 7},
  [30] = {.lex_state = 0, .external_lex_state = 6},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0, .external_lex_state = 8},
  [33] = {.lex_state = 0, .external_lex_state = 9},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0, .external_lex_state = 10},
  [36] = {.lex_state = 0, .external_lex_state = 10},
  [37] = {.lex_state = 0, .external_lex_state = 6},
  [38] = {.lex_state = 0, .external_lex_state = 11},
  [39] = {.lex_state = 0, .external_lex_state = 6},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 20},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 9},
  [44] = {.lex_state = 0, .external_lex_state = 6},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0, .external_lex_state = 7},
  [47] = {.lex_state = 0, .external_lex_state = 6},
  [48] = {.lex_state = 0, .external_lex_state = 6},
  [49] = {.lex_state = 0, .external_lex_state = 6},
  [50] = {.lex_state = 0, .external_lex_state = 6},
  [51] = {.lex_state = 0, .external_lex_state = 8},
  [52] = {.lex_state = 0, .external_lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_pod_command] = ACTIONS(1),
    [sym_begin_command] = ACTIONS(1),
    [sym_end_command] = ACTIONS(1),
    [sym_for_command] = ACTIONS(1),
    [sym_format_name] = ACTIONS(1),
    [sym_command] = ACTIONS(1),
    [sym_cut_command] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
    [sym__start_command] = ACTIONS(1),
    [sym__start_plain] = ACTIONS(1),
    [sym__start_verbatim] = ACTIONS(1),
    [sym__content_plain] = ACTIONS(1),
    [sym__intseq_letter] = ACTIONS(1),
    [sym__intseq_start] = ACTIONS(1),
    [sym__intseq_end] = ACTIONS(1),
    [sym__data_section] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_pod] = STATE(45),
    [sym_pod_paragraph] = STATE(2),
    [sym_begin_paragraph] = STATE(2),
    [sym_for_paragraph] = STATE(2),
    [sym_command_paragraph] = STATE(2),
    [sym_plain_paragraph] = STATE(2),
    [sym_verbatim_paragraph] = STATE(2),
    [sym_cut_paragraph] = STATE(2),
    [aux_sym_pod_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__blank_line] = ACTIONS(5),
    [sym__start_command] = ACTIONS(7),
    [sym__start_plain] = ACTIONS(9),
    [sym__start_verbatim] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      sym__start_command,
    ACTIONS(9), 1,
      sym__start_plain,
    ACTIONS(11), 1,
      sym__start_verbatim,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym__blank_line,
    STATE(3), 8,
      sym_pod_paragraph,
      sym_begin_paragraph,
      sym_for_paragraph,
      sym_command_paragraph,
      sym_plain_paragraph,
      sym_verbatim_paragraph,
      sym_cut_paragraph,
      aux_sym_pod_repeat1,
  [26] = 6,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym__blank_line,
    ACTIONS(22), 1,
      sym__start_command,
    ACTIONS(25), 1,
      sym__start_plain,
    ACTIONS(28), 1,
      sym__start_verbatim,
    STATE(3), 8,
      sym_pod_paragraph,
      sym_begin_paragraph,
      sym_for_paragraph,
      sym_command_paragraph,
      sym_plain_paragraph,
      sym_verbatim_paragraph,
      sym_cut_paragraph,
      aux_sym_pod_repeat1,
  [52] = 6,
    ACTIONS(31), 1,
      sym__eol,
    ACTIONS(33), 1,
      sym__content_plain,
    ACTIONS(35), 1,
      sym__intseq_letter,
    STATE(30), 1,
      sym_content,
    STATE(46), 1,
      sym_sequence_letter,
    STATE(9), 2,
      aux_sym__content,
      sym_interior_sequence,
  [72] = 6,
    ACTIONS(35), 1,
      sym__intseq_letter,
    ACTIONS(37), 1,
      sym__content_plain,
    ACTIONS(39), 1,
      sym__intseq_end,
    STATE(32), 1,
      sym_content,
    STATE(52), 1,
      sym_sequence_letter,
    STATE(11), 2,
      aux_sym__content,
      sym_interior_sequence,
  [92] = 6,
    ACTIONS(35), 1,
      sym__intseq_letter,
    ACTIONS(37), 1,
      sym__content_plain,
    ACTIONS(41), 1,
      sym__intseq_end,
    STATE(51), 1,
      sym_content,
    STATE(52), 1,
      sym_sequence_letter,
    STATE(11), 2,
      aux_sym__content,
      sym_interior_sequence,
  [112] = 5,
    ACTIONS(43), 1,
      sym__eol,
    ACTIONS(45), 1,
      sym__content_plain,
    ACTIONS(48), 1,
      sym__intseq_letter,
    STATE(46), 1,
      sym_sequence_letter,
    STATE(7), 2,
      aux_sym__content,
      sym_interior_sequence,
  [129] = 5,
    ACTIONS(33), 1,
      sym__content_plain,
    ACTIONS(35), 1,
      sym__intseq_letter,
    STATE(37), 1,
      sym_content,
    STATE(46), 1,
      sym_sequence_letter,
    STATE(9), 2,
      aux_sym__content,
      sym_interior_sequence,
  [146] = 5,
    ACTIONS(35), 1,
      sym__intseq_letter,
    ACTIONS(51), 1,
      sym__eol,
    ACTIONS(53), 1,
      sym__content_plain,
    STATE(46), 1,
      sym_sequence_letter,
    STATE(7), 2,
      aux_sym__content,
      sym_interior_sequence,
  [163] = 5,
    ACTIONS(43), 1,
      sym__intseq_end,
    ACTIONS(48), 1,
      sym__intseq_letter,
    ACTIONS(55), 1,
      sym__content_plain,
    STATE(52), 1,
      sym_sequence_letter,
    STATE(10), 2,
      aux_sym__content,
      sym_interior_sequence,
  [180] = 5,
    ACTIONS(35), 1,
      sym__intseq_letter,
    ACTIONS(51), 1,
      sym__intseq_end,
    ACTIONS(58), 1,
      sym__content_plain,
    STATE(52), 1,
      sym_sequence_letter,
    STATE(10), 2,
      aux_sym__content,
      sym_interior_sequence,
  [197] = 1,
    ACTIONS(60), 5,
      sym__start_command,
      sym__start_plain,
      sym__start_verbatim,
      ts_builtin_sym_end,
      sym__blank_line,
  [205] = 5,
    ACTIONS(62), 1,
      sym_pod_command,
    ACTIONS(64), 1,
      sym_begin_command,
    ACTIONS(66), 1,
      sym_for_command,
    ACTIONS(68), 1,
      sym_command,
    ACTIONS(70), 1,
      sym_cut_command,
  [221] = 1,
    ACTIONS(72), 5,
      sym__start_command,
      sym__start_plain,
      sym__start_verbatim,
      ts_builtin_sym_end,
      sym__blank_line,
  [229] = 1,
    ACTIONS(74), 5,
      sym__start_command,
      sym__start_plain,
      sym__start_verbatim,
      ts_builtin_sym_end,
      sym__blank_line,
  [237] = 1,
    ACTIONS(76), 5,
      sym__start_command,
      sym__start_plain,
      sym__start_verbatim,
      ts_builtin_sym_end,
      sym__blank_line,
  [245] = 1,
    ACTIONS(78), 5,
      sym__start_command,
      sym__start_plain,
      sym__start_verbatim,
      ts_builtin_sym_end,
      sym__blank_line,
  [253] = 1,
    ACTIONS(80), 5,
      sym__start_command,
      sym__start_plain,
      sym__start_verbatim,
      ts_builtin_sym_end,
      sym__blank_line,
  [261] = 1,
    ACTIONS(82), 5,
      sym__start_command,
      sym__start_plain,
      sym__start_verbatim,
      ts_builtin_sym_end,
      sym__blank_line,
  [269] = 1,
    ACTIONS(84), 5,
      sym__start_command,
      sym__start_plain,
      sym__start_verbatim,
      ts_builtin_sym_end,
      sym__blank_line,
  [277] = 1,
    ACTIONS(86), 5,
      sym__start_command,
      sym__start_plain,
      sym__start_verbatim,
      ts_builtin_sym_end,
      sym__blank_line,
  [285] = 1,
    ACTIONS(88), 3,
      sym__content_plain,
      sym__intseq_letter,
      sym__intseq_end,
  [291] = 1,
    ACTIONS(90), 3,
      sym__eol,
      sym__content_plain,
      sym__intseq_letter,
  [297] = 1,
    ACTIONS(88), 3,
      sym__eol,
      sym__content_plain,
      sym__intseq_letter,
  [303] = 1,
    ACTIONS(90), 3,
      sym__content_plain,
      sym__intseq_letter,
      sym__intseq_end,
  [309] = 2,
    ACTIONS(92), 1,
      aux_sym_begin_paragraph_token1,
    ACTIONS(94), 1,
      sym__eol,
  [316] = 1,
    ACTIONS(96), 1,
      sym_format_name,
  [320] = 1,
    ACTIONS(98), 1,
      aux_sym_begin_paragraph_token1,
  [324] = 1,
    ACTIONS(100), 1,
      sym__intseq_start,
  [328] = 1,
    ACTIONS(102), 1,
      sym__eol,
  [332] = 1,
    ACTIONS(104), 1,
      sym_format_name,
  [336] = 1,
    ACTIONS(106), 1,
      sym__intseq_end,
  [340] = 1,
    ACTIONS(108), 1,
      sym__data_section,
  [344] = 1,
    ACTIONS(110), 1,
      sym_format_name,
  [348] = 1,
    ACTIONS(112), 1,
      sym__content_plain,
  [352] = 1,
    ACTIONS(114), 1,
      sym__content_plain,
  [356] = 1,
    ACTIONS(116), 1,
      sym__eol,
  [360] = 1,
    ACTIONS(118), 1,
      sym__start_command,
  [364] = 1,
    ACTIONS(120), 1,
      sym__eol,
  [368] = 1,
    ACTIONS(122), 1,
      sym_end_command,
  [372] = 1,
    ACTIONS(124), 1,
      aux_sym_command_paragraph_token1,
  [376] = 1,
    ACTIONS(126), 1,
      aux_sym_begin_paragraph_token1,
  [380] = 1,
    ACTIONS(128), 1,
      aux_sym_begin_paragraph_token1,
  [384] = 1,
    ACTIONS(130), 1,
      sym__eol,
  [388] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [392] = 1,
    ACTIONS(134), 1,
      sym__intseq_start,
  [396] = 1,
    ACTIONS(136), 1,
      sym__eol,
  [400] = 1,
    ACTIONS(138), 1,
      sym__eol,
  [404] = 1,
    ACTIONS(140), 1,
      sym__eol,
  [408] = 1,
    ACTIONS(142), 1,
      sym__eol,
  [412] = 1,
    ACTIONS(144), 1,
      sym__intseq_end,
  [416] = 1,
    ACTIONS(146), 1,
      sym__intseq_start,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 92,
  [SMALL_STATE(7)] = 112,
  [SMALL_STATE(8)] = 129,
  [SMALL_STATE(9)] = 146,
  [SMALL_STATE(10)] = 163,
  [SMALL_STATE(11)] = 180,
  [SMALL_STATE(12)] = 197,
  [SMALL_STATE(13)] = 205,
  [SMALL_STATE(14)] = 221,
  [SMALL_STATE(15)] = 229,
  [SMALL_STATE(16)] = 237,
  [SMALL_STATE(17)] = 245,
  [SMALL_STATE(18)] = 253,
  [SMALL_STATE(19)] = 261,
  [SMALL_STATE(20)] = 269,
  [SMALL_STATE(21)] = 277,
  [SMALL_STATE(22)] = 285,
  [SMALL_STATE(23)] = 291,
  [SMALL_STATE(24)] = 297,
  [SMALL_STATE(25)] = 303,
  [SMALL_STATE(26)] = 309,
  [SMALL_STATE(27)] = 316,
  [SMALL_STATE(28)] = 320,
  [SMALL_STATE(29)] = 324,
  [SMALL_STATE(30)] = 328,
  [SMALL_STATE(31)] = 332,
  [SMALL_STATE(32)] = 336,
  [SMALL_STATE(33)] = 340,
  [SMALL_STATE(34)] = 344,
  [SMALL_STATE(35)] = 348,
  [SMALL_STATE(36)] = 352,
  [SMALL_STATE(37)] = 356,
  [SMALL_STATE(38)] = 360,
  [SMALL_STATE(39)] = 364,
  [SMALL_STATE(40)] = 368,
  [SMALL_STATE(41)] = 372,
  [SMALL_STATE(42)] = 376,
  [SMALL_STATE(43)] = 380,
  [SMALL_STATE(44)] = 384,
  [SMALL_STATE(45)] = 388,
  [SMALL_STATE(46)] = 392,
  [SMALL_STATE(47)] = 396,
  [SMALL_STATE(48)] = 400,
  [SMALL_STATE(49)] = 404,
  [SMALL_STATE(50)] = 408,
  [SMALL_STATE(51)] = 412,
  [SMALL_STATE(52)] = 416,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pod, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pod, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pod_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pod_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pod_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pod_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pod_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__content, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2, 0, 0), SHIFT_REPEAT(7),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2, 0, 0), SHIFT_REPEAT(29),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__content, 2, 0, 0), SHIFT_REPEAT(10),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pod_paragraph, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cut_paragraph, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_paragraph, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verbatim_paragraph, 3, 0, 1),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_paragraph, 4, 0, 2),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_paragraph, 5, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_paragraph, 5, 0, 4),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_paragraph, 7, 0, 5),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_begin_paragraph, 11, 0, 4),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interior_sequence, 4, 0, 3),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interior_sequence, 3, 0, 3),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence_letter, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [132] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__eol = 0,
  ts_external_token__start_command = 1,
  ts_external_token__start_plain = 2,
  ts_external_token__start_verbatim = 3,
  ts_external_token__content_plain = 4,
  ts_external_token__intseq_letter = 5,
  ts_external_token__intseq_start = 6,
  ts_external_token__intseq_end = 7,
  ts_external_token__data_section = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__eol] = sym__eol,
  [ts_external_token__start_command] = sym__start_command,
  [ts_external_token__start_plain] = sym__start_plain,
  [ts_external_token__start_verbatim] = sym__start_verbatim,
  [ts_external_token__content_plain] = sym__content_plain,
  [ts_external_token__intseq_letter] = sym__intseq_letter,
  [ts_external_token__intseq_start] = sym__intseq_start,
  [ts_external_token__intseq_end] = sym__intseq_end,
  [ts_external_token__data_section] = sym__data_section,
};

static const bool ts_external_scanner_states[12][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__eol] = true,
    [ts_external_token__start_command] = true,
    [ts_external_token__start_plain] = true,
    [ts_external_token__start_verbatim] = true,
    [ts_external_token__content_plain] = true,
    [ts_external_token__intseq_letter] = true,
    [ts_external_token__intseq_start] = true,
    [ts_external_token__intseq_end] = true,
    [ts_external_token__data_section] = true,
  },
  [2] = {
    [ts_external_token__start_command] = true,
    [ts_external_token__start_plain] = true,
    [ts_external_token__start_verbatim] = true,
  },
  [3] = {
    [ts_external_token__eol] = true,
    [ts_external_token__content_plain] = true,
    [ts_external_token__intseq_letter] = true,
  },
  [4] = {
    [ts_external_token__content_plain] = true,
    [ts_external_token__intseq_letter] = true,
    [ts_external_token__intseq_end] = true,
  },
  [5] = {
    [ts_external_token__content_plain] = true,
    [ts_external_token__intseq_letter] = true,
  },
  [6] = {
    [ts_external_token__eol] = true,
  },
  [7] = {
    [ts_external_token__intseq_start] = true,
  },
  [8] = {
    [ts_external_token__intseq_end] = true,
  },
  [9] = {
    [ts_external_token__data_section] = true,
  },
  [10] = {
    [ts_external_token__content_plain] = true,
  },
  [11] = {
    [ts_external_token__start_command] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_pod_external_scanner_create(void);
void tree_sitter_pod_external_scanner_destroy(void *);
bool tree_sitter_pod_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_pod_external_scanner_serialize(void *, char *);
void tree_sitter_pod_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pod(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_pod_external_scanner_create,
      tree_sitter_pod_external_scanner_destroy,
      tree_sitter_pod_external_scanner_scan,
      tree_sitter_pod_external_scanner_serialize,
      tree_sitter_pod_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "pod",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
